services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: navy-backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_TEXT_MODEL=${GEMINI_TEXT_MODEL:-gemini-2.5-flash}
      - GEMINI_EMBED_MODEL=${GEMINI_EMBED_MODEL:-gemini-embedding-2-preview}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
    restart: unless-stopped
    networks:
      - navy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        NEXT_PUBLIC_API_URL: http://34.173.34.205:8000
    container_name: navy-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_API_URL=http://34.173.34.205:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - navy-network

networks:
  navy-network:
    driver: bridge
